server:
  port: 80
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/codingbat
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: abdualievdev666@gmail.com
    password: gyxlcnucndnktbjt
    port: '587'

#  mail:
#    host: smtp.gmail.com
#    password: gyxlcnucndnktbjt
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    username: abdualievdev666@gmail.com
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access:
    key: 3XpdXc*765Pzi!jl8buv7QsBaOl!pUNdtVnCc#kf6ihD5G*^U%
    expirationTime: 72000000
  refresh:
    key: 3XpdXc*765Pzidasdlas;kdasjdlashda!jl8buv7QsBaOl!#kf6ihD5G*^U%
    expirationTime: 604800000