server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/codingbat
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
mail:
  host=smtp:
    gmail:
      com:
  port: 587
  username: procodinguz@gmail.com
  password: xkbnejslrdhpqzeb
  properties:
    mail:
      smtp:
        auth=true
      starttls:
        enable=true
jwt:
  key: 3XpdXc*765Pzi!jl8buv7QsBaOl!pUNdtVnCc#kf6ihD5G*^U%