server:
  port: 80

spring:
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/codingbat
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true